# Generated by Django 5.2 on 2025-04-15 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('days', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'approval_done',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('first_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('second_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('final_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('reception_info', models.CharField(blank=True, max_length=255, null=True)),
                ('replacement', models.CharField(blank=True, max_length=100, null=True)),
                ('timekeeper', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'approval_process',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NameDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'name_dictionary',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistrationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('entered_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'registration_queue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('vacation_days', models.FloatField(default=0)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('is_hr', models.BooleanField(default=False)),
                ('is_director', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('vacation_type', models.CharField(choices=[('annual', 'Ежегодный'), ('unpaid', 'Без сохранения'), ('study', 'Учебный')], default='annual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacation_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('vacation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_second', to='vacation.vacationrequest')),
            ],
            options={
                'db_table': 'approval_second',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('vacation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_first', to='vacation.vacationrequest')),
            ],
            options={
                'db_table': 'approval_first',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('vacation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_final', to='vacation.vacationrequest')),
            ],
            options={
                'db_table': 'approval_final',
                'managed': True,
            },
        ),
    ]
