# Generated by Django 5.2 on 2025-04-11 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('days', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'approval_done',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('days', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'approval_final',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('days', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'approval_first',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('first_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('second_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('final_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('reception_info', models.CharField(blank=True, max_length=255, null=True)),
                ('replacement', models.CharField(blank=True, max_length=100, null=True)),
                ('timekeeper', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'approval_process',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_approval', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('days', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'approval_second',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NameDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'name_dictionary',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='registrationqueue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
